import '@/styles/globals.css';
import type { Metadata } from 'next';
import { IBM_Plex_Sans_JP } from 'next/font/google';
import type React from 'react';

const ibmPlexSansJP = IBM_Plex_Sans_JP({
  variable: '--font-ibm-plex-sans-jp',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${ibmPlexSansJP.variable}`}>{children}</body>
    </html>
  );
}
